# Generated by Django 3.2.8 on 2022-09-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20220920_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_mates', to='team.team'),
        ),
    ]
