# Generated by Django 3.2.8 on 2022-09-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammate_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
