# Generated by Django 3.2.8 on 2022-10-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='amount',
            field=models.IntegerField(blank=True, default=40000, null=True),
        ),
    ]
