# Generated by Django 3.2.8 on 2022-10-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
